### ISSUE TITLE
80 character max per line

### ISSUE THREAD

**Issue by yannickkiki** [the-bridge/info-sourouk#1]
Salut @sourouk . L'exercice a demandé d'écrire au maximum 80 lignes par caractères et vous pouvez faire le réglage dans votre éditeur de telle sorte qu'il passe à la ligne automatiquement après un certain nombre de caractères. 
Sur ta ligne 7, ça excède les 80 caractères, donc essaies d'arranger ça

Tu peux mettre par exemple:

`print ("I'am {}, an active member of Ceceonat\n Email: {}\n Logins:\n \t Github: {}\n \t Gitlab: {}\n \t"\`
`"Programming language: {} ".format(name,email,github_login,gitlab_login,language))`
.. ça devrait résoudre le problème

**Comment by sourouk** [comment]
merci

**Comment by sourouk** [comment]
comment limiter le nombre de caractère sur une ligne avec Vim ?

**Comment by yannickkiki** [comment]
> comment limiter le nombre de caractère sur une ligne avec Vim ?

Aucune idée.. Dis moi si tu trouves
